<?php /** @var Manugentoo\Testimonials\Block\ListTestimonials $block **/ ?>
<div class="testimonials-module">
	<div class="grid-container">
		<div class="grid-x grid-padding-x">
			<div class="small-12 text-center">
				<h4>What Our Happy Customers Are Saying</h4>
			</div>
		</div>
	</div>
	<div class="grid-container">
		<div class="grid-x grid-padding-x">
			<div class="orbit" role="region" aria-label="What Our Happy Customers Are Saying" data-orbit>
				<div class="orbit-wrapper">
					<div class="orbit-controls">
						<button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
						<button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
					</div>
					<ul class="orbit-container">
						<?php foreach($block->getTestimonials() as $testimonial):?>
                            <li class="is-active orbit-slide">
                                <div class="item text-center">
                                    <div class="image text-center">
                                        <img src="<?=$block->getTestimonialsImageUrl($testimonial->getData('company_image'))?>">
                                    </div>
                                    <div class="customer-says">
                                        <?=$testimonial->getData('comment')?>
                                    </div>
                                    <p class="customer"><?=$testimonial->getData('name')?><br><?=$testimonial->getData('company_name')?></p>
                                </div>
                            </li>
						<?php endforeach;?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
